openapi: 3.1.0
info:
  title: API do DAN
  description: API multifuncional com integração a IA, GitHub, Google Drive, Azure DevOps, automação, Zapier e Render.com.
  version: "1.0"

servers:
  - url: https://server-apig-gpt-1.onrender.com
    description: Servidor principal da API do DAN

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
