
name: memory_merge
on:
  push:
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
      - '**/*.xml'
      - '**/*.pdf'
jobs: 
  merge_memory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Executa Merge de Memoria
        run: curl -X POST http://localhost:1000/merge-memory -H 'Content-Type: application/json' -d {"source": "file", "content": "Arquivo modificado via workflow"}